model/form.js
for https://github.com/AdvancedPhotonSource/traveler/issues/6
=> use attr to get string

model/form.js, public/javascripts/form-builder.js
Client side unique userkey validation ready
also message from server side validation
=> Enhance 5 validatin

public/javascripts/form-config.js
fix https://github.com/AdvancedPhotonSource/traveler/issues/20
=> enable add button after ajax

public/javascripts/form-builder.js, public/javascripts/form-config.js, public/javascripts/table.js, public/javascripts/traveler-config.js, public/javascripts/traveler.js, public/javascripts/travelers.js, routes/traveler.js, views/traveler-config.jade
add tags to traveler config, and tables
=> Traveler tags

public/javascripts/binders.js, public/javascripts/forms.js, public/javascripts/travelers.js
for binder, form, and traveler
=> fix profile image display when user image not available

public/javascripts/public-forms.js
=> fix public form user profile image

routes/form.js
=> copy all tags together when cloning a form

docker/ad.json, public/javascripts/share.js, views/main.jade
fix https://github.com/AdvancedPhotonSource/traveler/issues/46
need to `docker-compose build` then start to have the ad config change
=> fix js load issue and ad config

app.js, lib/req-utils.js, model/binder.js, model/traveler.js, public/javascripts/binder-config.js, public/javascripts/binder-viewer.js, public/javascripts/binders.js, public/javascripts/form-manager.js, public/javascripts/report-binder.js, public/javascripts/table.js, public/javascripts/traveler-form-loader.js, public/javascripts/traveler.js, public/javascripts/travelers.js, routes/binder.js, routes/report.js, routes/traveler.js, utilities/routes.js, views/binder-input-progress.jade, views/binder-value-progress.jade, views/binder.jade, views/report-binder.jade, views/traveler-viewer.jade, views/traveler.jade
first use a form with user defined keys and the `mapping` to create several travelers. 
create a binder with the travelers. 
add data to the travelers. 
on the binder page like 
click the `generate report` button, and a report will be generated like 
The table can be exported as csv file or printed to pdf. 
We need more design work for 
1. how to sort the keys/columns from left to right on the report
2. how to generate a report for a set of travelers that is not in a binder. I assume we can allow them to search (by tag, or key, or by anything), then choose, and then generate
=> Table report userkey

public/javascripts/report-binder.js, routes/traveler.js
add a new `/travelers/:id/keyvalue/json` endpoint for data with user defined key value
=> new keyvalue endpoint and update report

routes/api.js, routes/main.js
implement https://github.com/AdvancedPhotonSource/traveler/issues/75
the urls are 
`https://localhost:3443/apis/keys/travelers/`
`https://localhost:3443/apis/tags/travelers/`
=> Api tags keys

public/javascripts/binder-viewer.js, public/javascripts/report.js, public/javascripts/table.js, public/stylesheets/style.css, routes/binder.js, routes/report.js, views/report-travelers.jade
fix the second part of https://github.com/AdvancedPhotonSource/traveler/issues/67
=> Binder tag key

public/javascripts/report.js, public/javascripts/table.js, public/stylesheets/style.css, routes/report.js, views/report-travelers.jade
this fixes the report control part of https://github.com/AdvancedPhotonSource/traveler/issues/67
use can control the report table, and export as the visual result
=> Report column control

routes/api.js
for https://github.com/AdvancedPhotonSource/traveler/issues/74
=> add keyvalue to api

public/javascripts/report.js, public/javascripts/table.js, routes/api.js, routes/traveler.js
put user defined keys in `user_defined` in order to avoid naming conflict.
=> Seperate userkey

public/javascripts/binder-viewer.js, public/javascripts/travelers.js
fix https://github.com/AdvancedPhotonSource/traveler/issues/78
=> empty form before a new submit

public/javascripts/traveler.js
fix https://github.com/AdvancedPhotonSource/traveler/issues/79
=> Fix radio validation 79

lib/error.js, model/traveler.js, routes/form.js, routes/traveler.js
fix https://github.com/AdvancedPhotonSource/traveler/issues/80
=> Fix number validation 80

builderview/userkey.jade, inputview/number.jade, public/builder/input.js, public/javascripts/form-builder.js
implement https://github.com/AdvancedPhotonSource/traveler/issues/71
=> add number range help

views/report-travelers.jade
for https://github.com/AdvancedPhotonSource/traveler/issues/89
=> correct the template

docker/ad.json, views/binders.jade, views/forms.jade
for https://github.com/AdvancedPhotonSource/traveler/issues/48
need to rebuild the container for the change to take effect 
```
docker-compose down
docker-compose build
docker-compose up
```
=> update docker config

docker/ad.json, model/form.js, model/traveler.js, public/dependencies/lodash.js, public/javascripts/report.js, public/javascripts/table.js, routes/api.js, routes/traveler.js, views/binders.jade, views/forms.jade, views/layout.jade, views/report-travelers.jade
add labels to models and reports
=> Label report 85

public/javascripts/public-travelers.js, views/public-travelers.jade
=> add support to report public travelers

public/javascripts/public-binders.js
easy fix for https://github.com/AdvancedPhotonSource/traveler/issues/102
The column name was changed, which resulted the table could that load.
=> fix missing col

.eslintrc, lib/req-utils.js, model/form.js, package-lock.json, package.json, routes/form.js, test/lib/ldap-client-test.js, test/lib/req-utils-test.js
for https://github.com/AdvancedPhotonSource/traveler/issues/117
=> 117 form status

.dockerignore, Dockerfile, docker-compose.yml, lib/auth.js, lib/req-utils.js, model/form.js, nodemon.json, package.json, routes/admin.js, routes/api.js, routes/form.js, utilities/routes.js, views/form-new.jade
this addresses https://github.com/AdvancedPhotonSource/traveler/issues/133
=> Form type 133

public/javascripts/form-builder.js
this fixes https://github.com/AdvancedPhotonSource/traveler/issues/145
=> fix user key

lib/error.js, model/binder.js, model/form.js, model/traveler.js, public/javascripts/binders.js, public/javascripts/discrepancy-form-manager.js, public/javascripts/form-builder.js, public/javascripts/form-management.js, public/javascripts/form-manager.js, public/javascripts/forms.js, public/javascripts/table-action.js, public/javascripts/table.js, public/javascripts/traveler.js, public/javascripts/travelers.js, routes/api.js, routes/form-management.js, routes/form.js, routes/traveler.js, utilities/routes.js, views/discrepancy-form-manager.jade, views/form-builder.jade, views/form-management.jade, views/form-new.jade, views/forms.jade, views/traveler-config.jade, views/traveler.jade, views/travelers.jade
The change supports the follow workflow: 
1. create a discrepancy form, and have it approved to release. 
2. add an discrepancy form to an existing traveler from the discrepancy form manager page
3. add data/notes to the discrepancy form within the traveler.
=> Discrepancy 149

public/javascripts/form-viewer.js, public/javascripts/traveler-form-loader.js, public/javascripts/traveler-viewer.js, public/javascripts/traveler.js, public/javascripts/util.js, public/stylesheets/style.css, views/form-manager.jade, views/form-viewer.jade, views/traveler-viewer.jade, views/traveler.jade
=> Add title to sidebar

lib/auth.js, lib/req-utils.js, model/traveler.js, public/javascripts/discrepancy-form-manager.js, public/javascripts/forms.js, public/javascripts/traveler-discrepancy-form-loader.js, public/javascripts/traveler.js, public/javascripts/util.js, routes/form.js, routes/traveler.js, views/discrepancy-form-manager.jade, views/traveler.jade
The discrepancy log is rendered in table in both traveler and the form manager.
=> Discrepancy table 162

public/javascripts/discrepancy-form-manager.js
this fixes https://github.com/AdvancedPhotonSource/traveler/issues/165
=> manage the discrepancy forms

public/javascripts/form-builder.js, public/javascripts/traveler-discrepancy-form-loader.js, routes/api.js, routes/form.js, routes/traveler.js, views/form-builder.jade
fix https://github.com/AdvancedPhotonSource/traveler/issues/170
https://github.com/AdvancedPhotonSource/traveler/issues/169
and implement 
https://github.com/AdvancedPhotonSource/traveler/issues/172
e.g. https://localhost:3443/apis/travelers/5cb734f5b4b6c00943e203d3/log/
=> Discrepancy api 172

public/javascripts/traveler-discrepancy-form-loader.js, public/javascripts/traveler.js
resolve https://github.com/AdvancedPhotonSource/traveler/issues/171
=> default no use key in discrepancy

routes/api.js
this fixes
https://github.com/AdvancedPhotonSource/traveler/issues/174
and
https://github.com/AdvancedPhotonSource/traveler/issues/175
=> output active discrepancy form and corresponding logs

inputview/checkbox.jade, inputview/number.jade, inputview/radiogroup.jade, inputview/section.jade, inputview/text.jade, inputview/textarea.jade, inputview/upload.jade, lib/req-utils.js, package-lock.json, public/builder/input.js, public/builder/spec.js, public/javascripts/form-builder.js, routes/form.js
- section and control numbering added
- numbers updated when new element added or removed
- old forms do not get the numbers, but will have after editing with the new form builder
=> Control number 181

model/form.js
fix https://github.com/AdvancedPhotonSource/traveler/issues/190
=> only model label

public/javascripts/form-management.js, public/javascripts/forms.js, public/javascripts/public-forms.js, routes/form-management.js, routes/form.js
for https://github.com/AdvancedPhotonSource/traveler/issues/188
=> Form status 188

public/javascripts/form-management.js, public/javascripts/forms.js, public/javascripts/public-forms.js, routes/form-management.js, routes/form.js
for https://github.com/AdvancedPhotonSource/traveler/issues/189
=> Form type 189

public/javascripts/form-management.js, public/javascripts/forms.js, public/javascripts/public-forms.js, routes/form-management.js, routes/form.js, views/form-builder.jade
for https://github.com/AdvancedPhotonSource/traveler/issues/211
=> Form release 211

lib/ldap-client.js, model/history.js, public/javascripts/form-management.js, public/javascripts/forms.js, public/javascripts/public-forms.js, routes/form-management.js, routes/form.js, utilities/routes.js, views/form-builder.jade, views/forms.jade
for https://github.com/AdvancedPhotonSource/traveler/issues/186
=> Traveler release 186

lib/ldap-client.js, model/history.js, public/javascripts/form-management.js, public/javascripts/forms.js, public/javascripts/public-forms.js, routes/form-management.js, routes/form.js, utilities/routes.js, views/form-builder.jade, views/forms.jade
for https://github.com/AdvancedPhotonSource/traveler/issues/214
=> Form version 214

routes/traveler.js, views/forms.jade
fix https://github.com/AdvancedPhotonSource/traveler/issues/228
=> Travel fix 228

lib/req-utils.js, public/javascripts/forms.js, routes/form.js, routes/traveler.js, views/forms.jade
fix https://github.com/AdvancedPhotonSource/traveler/issues/232
=> Clone fix 232

public/javascripts/form-management.js, public/javascripts/forms.js, routes/form-management.js, views/forms.jade
resolve https://github.com/AdvancedPhotonSource/traveler/issues/240
=> add archived released table to normal user forms view

public/javascripts/form-management.js, public/javascripts/forms.js, routes/form-management.js, routes/form.js, views/forms.jade
resolve https://github.com/AdvancedPhotonSource/traveler/issues/233
=> Release check 233

inputview/upload.jade, public/builder/input.js, public/javascripts/form-builder.js, public/javascripts/forms.js, views/forms.jade, views/public-forms.jade
resolve https://github.com/AdvancedPhotonSource/traveler/issues/242
=> Required file 242

inputview/upload.jade, model/traveler.js, public/builder/input.js, public/javascripts/form-builder.js, public/javascripts/forms.js, public/javascripts/traveler-discrepancy-form-loader.js, public/javascripts/traveler.js, routes/traveler.js, views/forms.jade, views/public-forms.jade
resolve https://github.com/AdvancedPhotonSource/traveler/issues/200
=> Discrepancy file 200

routes/traveler.js
fix https://github.com/AdvancedPhotonSource/traveler/issues/265
=> user who can write can submit a traveler

public/javascripts/traveler.js, public/javascripts/validation.js, views/traveler.jade
for https://github.com/AdvancedPhotonSource/traveler/issues/260
=> File validation 260

lib/auth.js, lib/ldap-client.js, package-lock.json, public/javascripts/traveler.js, public/javascripts/validation.js, public/stylesheets/style.css
for https://github.com/AdvancedPhotonSource/traveler/issues/261
=> Discrepancy validate 261

public/javascripts/forms.js, routes/form-management.js, views/released-form.jade
fix https://github.com/AdvancedPhotonSource/traveler/issues/259
=> Form status 259

.gitignore, config/config.js, package-lock.json, utilities/mqtt.js
lint and reformat. 
run `docker-compose build --no-cache` to have new dep in the docker image.
=> update and clean
